<a href="https://colab.research.google.com/github/vikasmastud7/machinelearning/blob/master/Assignment03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Assignment 3</h1>
<h2>Task 1:<h2>
<h3>Q 1.</h3>
<p>Write a function to compute 5/0 and use try/except to catch the exceptions.</p>

In [0]:
def safe_division(num1 , num2):
  ans = 0
  try:
    return num1/num2
  except ZeroDivisionError:
    return 0

assert safe_division(5,0) == 0
assert safe_division(10,2) == 5

<h3>Q2.</h3>
<p>Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].</p><p>
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]</p>
<h3>Output should come as below:</h3>
<p>Americans play Baseball.<br>
Americans play Cricket.<br>
Americans watch Baseball.<br>
Americans watch Cricket.<br>
Indians play Baseball.<br>
Indians play Cricket.<br>
Indians watch Baseball.<br>
Indians watch Cricket.<br></p>

In [6]:
def sentences_generator(subject , verb, objects):
  for sub in subject:
    for v in verb:
      for obj in objects:
        yield sub , v , obj
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in sentences_generator(subjects, verbs,objects):
  print(" ".join(i))

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


<h1>Task 2:</h1>
<h3>Q 1.</h3>
<p>
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.<br>
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.
</p>

In [7]:
import numpy as np
def vander( x , N = None, increasing = False):
  if x == []:
    return []
  else:
    try:
      assert type(x) == list
      assert type(x[0]) != list
    except :
      raise ValueError("x must be a one-dimensional array or sequence.")
  if N == None:
    N = len(x)
  if increasing:
    ans = [ [ j ** i for j in x] for i in range(N) ]
  else:
    ans = [ [ j ** (N -1 - i) for j in x] for i in range(N) ]
  ans = np.array(ans).T
  return ans

x = [1,2,3,4,5, 6]
N = 4

print(vander(x),"\n")
print(vander(x, N),"\n")
print(vander(x, N , increasing= True),"\n")

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]] 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]] 

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]] 

