<a href="https://colab.research.google.com/github/vikasmastud7/machinelearning/blob/master/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [0]:
import numpy as np
def vander( x , N = None, increasing = False):
  if x == []:
    return []
  else:
    try:
      assert type(x) == list
      assert type(x[0]) != list
    except :
      raise ValueError("x must be a one-dimensional array or sequence.")
  if N == None:
    N = len(x)
  if increasing:
    ans = [ [ j ** i for j in x] for i in range(N) ]
  else:
    ans = [ [ j ** (N -1 - i) for j in x] for i in range(N) ]
  ans = np.array(ans).T
  return ans

x = [1,2,3,4,5, 6]
N = 4

print(vander(x),"\n")
print(vander(x, N),"\n")
print(vander(x, N , increasing= True),"\n")

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]] 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]] 

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]] 



Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [0]:
def moving_avg(arr , w):
  if arr == []:
    return []
  assert len(arr) > w
  l = len(arr) - w +1
  mov_avg = []
  y1 = sum(arr[:w])
  mov_avg.append(y1)
  l = 0
  r = w
  ans = y1
  while r < len(arr):
    ans = ans - arr[l] + arr[r]
    mov_avg.append(ans)
    r +=1
    l +=1
  return np.array(mov_avg)/w

moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])